### ISSUE TITLE
1주차 설계

### ISSUE THREAD

**Issue by saejinpark** [masters2023-project-03-second-hand/second-hand-max-fe#1]
# 설계

## 유저 시나리오
[유저 플로우 피그마](https://www.figma.com/file/oXwkTMpk6nmV2S0bCzSkQo/%EC%9C%A0%EC%A0%80-%ED%94%8C%EB%A1%9C%EC%9A%B0?type=whiteboard&node-id=103-6&t=fYS2m9MKhIQ1IA9N-0)

## 기술스택 선정
React: 사용자 인터페이스 구축
Vite: 웹 개발 빌드 도구
react-router-dom: 라우팅 관리
styled-components: 컴포넌트 스타일링
svgr: SVG를 React 컴포넌트로 변환
TypeScript: 정적 타입 검사
msw: 프론트엔드 API 모킹
Jest: 테스팅 프레임워크
react-query: 데이터 가져오기 및 캐싱

### 1주차

- 내 계정 (1주차)
    - 프로필 사진 편집
    - 회원가입 - OAuth, jwt/session
    - 로그인 -
    - 로그아웃 -
- 상품 목록 화면 (1주차, 2주차)

### 2주차

- 상품 목록 화면 (1주차, 2주차)
- 상품 등록 (2주차)
- 카테고리 목록 (2주차)
- 상품 상세 페이지 (2주차)
    - 판매자
    - 구매자

### 3주차

- 지역(동네) 설정 (3주차)
    - 지역(동네) 목록
    - 지역(동네) 추가 / 삭제
    - [동네 이름 API](https://sgis.kostat.go.kr/developer/html/newOpenApi/api/dataApi/addressBoundary.html)
- 판매 내역 목록 (3주차)
- 관심 상품 목록 (3주차)

### 4, 5주차

- 채팅 (4-5주차)

### 6주차

- 리팩토링

**Comment by Jerome-Yoo** [comment]
안녕하세요 구경왔습니다

**Comment by Jerome-Yoo** [comment]
깜찍한 도구 선정이 있었군요. `react-query: 데이터 가져오기 및 캐싱, msw: 프론트엔드 API 모킹`
회사에서 명확한 이유를 물어보는 주제 중 하나예요. 이런 맥락도 다음 PR에서는 같이 보내주세용
